### ISSUE TITLE
Python3.8 wheel not pushed to pypi for v2.1.0

### ISSUE THREAD

**Issue by jccurtis** [underworldcode/stripy#101]
The wheel for `python3.8` where not uploaded to `pypi` with the last release: https://pypi.org/project/stripy/2.1.0/#files

This causes issues on machines without `gfortran` which previously could install on `python3.8`. The CI must have changed to not push this like previously?

**Comment by jccurtis** [comment]
Also, related to #97

**Comment by lmoresi** [comment]
Just having a quick look ... which platform ?

The MacOS ones seemed to build and upload, the windows and linux are patchy. I am not sure why.

@brmather, @rbeucher

**Comment by jccurtis** [comment]
Thanks for taking a looking @lmoresi! I'm referring to the files uploaded to [pypi](https://pypi.org/project/stripy/#files) which appear to only be for cpython 3.7:

<img width="528" alt="CleanShot 2022-03-28 at 17 34 21@2x" src="https://user-images.githubusercontent.com/1504659/160509488-c4acba7d-a350-43fd-82a6-23a6f3f688ab.png">

I think I found the bug: https://github.com/underworldcode/stripy/blob/master/.github/workflows/python_pypi_upload_macos_wheel.yml#L50

I'm submitted a patch now ...

**Comment by jccurtis** [comment]
@lmoresi I haven't tested this PR's actions but I think it will fix the issues for the macOS and manylinux wheels for python 2.7, 3.6, 3.7, 3.8, 3.9

**Comment by lmoresi** [comment]
That's a good idea. We use this idea in other repos (though it takes a while to propagate because it has to be in the master/main branch for it to work anywhere. Let's see if it works.

**Comment by rbeucher** [comment]
Should be good now. Including for python 3.9, 3,10 on Linux. Mac and Windows.
