### ISSUE TITLE
stripy version `2.3` on pypi does not seem to be against a tag in github

### ISSUE THREAD

**Issue by bamartin125** [underworldcode/stripy#110]
pypi.org (https://pypi.org/project/stripy/2.3) reports that the `2.3` "release" was made on November 20th, 2023, but I do not see a related tag or release in github. I did however notice that the `2.3` source distribution attempts to build via the meson build system and that [this PR](https://github.com/underworldcode/stripy/pull/109) attempts to add that functionality.

Is pypi's `stripy` `2.3` a "published" version of what is on that PR?

**Comment by brmather** [comment]
I think that was a mistake in the PR. Just stick with stripy 2.2 for now.
