### ISSUE TITLE
stripy version `2.3` on pypi doesn't contain all built distributions

### ISSUE THREAD

**Issue by bamartin125** [underworldcode/stripy#111]
https://pypi.org/project/stripy/2.3/#files reports that only distributions for `macosx` have been published for `stripy` version `2.3`. pypi.org reports that the `2.3` "release" was made on November 20th, 2023.

Is this expected?

**Comment by brmather** [comment]
Just stick with stripy 2.2 for now. A proper 2.3 release (or 2.3.1) will hopefully roll out before Xmas. This will be compatible with python 3.12
