### ISSUE TITLE
[REVIEW] References on paper

### ISSUE THREAD

**Issue by santisoler** [underworldcode/stripy#14]
Part of https://github.com/openjournals/joss-reviews/issues/1410

The `paper.md` satisfies all JOSS requirements, it's very well written and the
*statement of need* is very clear within the first two paragraphs.
Nice work! :+1:

I have just one doubt. Does the *Laske, G., Masters, G., Ma, Z., & Pasyanos, M.
(2013)* article has a DOI? I haven't been able to find it through a quick search, but if you
have it, would be nice to add it.

JOSS requires that referenced papers, datasets and softwares must have a DOI, but don't
know what's the policy about abstracts.
In case you can't find a DOI for *Laske et al. (2013)* we could ask the editors what
should we do.

**Comment by lmoresi** [comment]
The alternative is to cite the web address where the dataset is available or the URL of the abstract PDF. But the Abstract has a large number of citations in the form we have used and no obvious way to find a DOI. I went back to the original location here: https://meetingorganizer.copernicus.org/EGU2013/posters/12567 and https://meetingorganizer.copernicus.org/EGU2013/EGU2013-2658.pdf 

Maybe one day the EGU will back-issue DOIs

**Comment by lmoresi** [comment]
PS - I'll leave this open until there is editorial feedback.

**Comment by santisoler** [comment]
@VivianePons, we have a minor doubt regarding one of the references. Neither the authors nor me could be able to find a DOI for *Laske, G., Masters, G., Ma, Z., & Pasyanos, M. (2013)*.
Can they keep it without a DOI? Can they just add a link to the PDF version of the article instead?

**Comment by VivianePons** [comment]
Yes, you can keep it without DOI if it does not exist

**Comment by santisoler** [comment]
Thanks @VivianePons!

**Comment by santisoler** [comment]
@lmoresi @brmather In light of this editorial feedback, we can safely close this issue if you agree.

**Comment by lmoresi** [comment]
I'm fine with that !
