### ISSUE TITLE
[REVIEW] License

### ISSUE THREAD

**Issue by santisoler** [underworldcode/stripy#15]
I see you have chosen the LGPL v3 license for your software. Great choice! :+1:
I think the license is well applied according to the **gnu.org** requirements.
You added:
- the `COPYING` file,
- the `COPYING.LESSER` file,
- license notes to each code file.

I would only change the [`License.txt`](https://github.com/underworldcode/stripy/blob/paper/Licence.txt) file for the one that GitHub offers you to specify the software is released under LGPL v3. If you do it, GitHub will recognize the license and add it to the metadata of the repo. This makes easier to search software by license inside GitHub.

See how Github shows the license of [verde](www.github.com/fatiando/verde) and [yellowbrick](https://github.com/DistrictDataLabs/yellowbrick) on the top bar along with **Commits**, **Branches**, **Releases**.

![screen-verde-license](https://user-images.githubusercontent.com/11541317/56760285-40583a00-6771-11e9-9195-c7350064a22e.jpg)
![screen-yellowbrick-license](https://user-images.githubusercontent.com/11541317/56760459-94631e80-6771-11e9-935e-25fa156404be.jpg)

You can read [this article](https://help.github.com/en/articles/adding-a-license-to-a-repository) for more instructions on how to add a `LICENSE` file in a quick way.

If you have any doubts, don't hesitate to ask for help.

**Comment by lmoresi** [comment]
Zenodo also likes this better, I believe, so we will take the suggestion on board.

**Comment by santisoler** [comment]
Great! Because it's expected the `LICENSE` file to be on the root of the repo, most online tools (like GitHub or Zenodo) will try to read it from that location.

I would recommend to reopen this issue until is fixed so we don't forget to tackle it down.

**Comment by santisoler** [comment]
Sorry, I've just seen that you fixed this on the `master` branch.
Leave this issue closed then, sorry for the inconvenience.
