### ISSUE TITLE
[REVIEW] Installation

### ISSUE THREAD

**Issue by santisoler** [underworldcode/stripy#17]
I really liked the installation instructions: they offers different ways to get `stripy`
working, which is an easy way to encourage users to use it.
I'm more familiar with `pip` package manager than `docker`, although many users would be
very thankful to have this option in case they don't want to bother installing
`gfortran` or having to reconfigure the build if they are using another Fortran
compiler.

I think the **installation instructions requirements of JOSS are already satisfied**,
although I would like to propose some minor changes, specially with
the non-`docker` way.

1. I would specify which minimum Python version is needed. Nowdays everyone is leaving
   Python 2.7 behind because its End of Life is less than a year ahead, so one would
   expect `stripy` to run under Python 3, but would be nice to make it clearer,
   e.g. *You'll need Python 3.5 or greater.*
2. The dependencies can be specified using markdown lists instead of having them on
   a plain sentence.
   For example:
   ```
   ### Dependencies
   - gfortran
   - numpy
   ```
3. The `docker` and the non-`docker` instructions can be included under the same
   **Installation** section, creating a subsection for each installation method.
   So, one could create a subsection called **Installing with pip**, another one like
   **Installing the latest development version** and **Installing with Docker**.
   See [Verde's installation instructions](https://www.fatiando.org/verde/latest/install.html) for inspiration.
4. I think the `python setup.py build && python setup.py install` instructions are
   not the best choice for end users. In my opinion is better to work with `pip` because
   it have great tools to install, uninstall or update your package.
   So I would just leave the `pip` instructions for the sake of convenience.
   If there's any reason why you think you should keep the `python setup.py ...`
   instructions, please let me know.

I'll open a Pull Request applying this modifications so you can then review the changes
and we can discuss there if you agree with them.

## Minor versioning issue

There's a minor issue regarding the release version of the installed package.
If I install `stripy` through `pip` by downloading the latest version on `pypi.org`:
```
pip install stripy
```
I get the `0.7.0` version.
But, if I download the latest version, say the `HEAD` of `paper` branch, it's signed as
the `0.7.0` version although there could be differences with the proper `0.7.0` version.

The problem raises because the `version` field on `setup.py` is hardcoded to
`0.7.0`.
One way to solve this is to hardcode the `version` field to something like `0.7.0-dev`
for non releases commits, and change it only on commits that will be released according
to its version number.
Another way is to automatize the value of the `version` field.
For example, [`verde`](https://www.github.com/fatiando/verde) sets the version based on the hash of the current commit,
which comes very handy when debugging.

This is a good feature to add, but **won't be required to submit the paper to JOSS**.
I just wanted to pointed it out in case you're interested.
If you want, we could leave this as final step before publication, or even after it gets
published.
I can help you implementing it.

**Comment by lmoresi** [comment]
I would like to address this issue and, perhaps the one with the docker images having more helpful tagging. It would be best to have tags sync'd between docker and pypi. 

How does commit-based tagging work with pip where there is an implied ordering of the tags to make >= operations meaningful ? 

Happy to address this offline if it will blow out the review thread.

**Comment by santisoler** [comment]
I've just added a comment on #16. It's somehow related to this one, so please read it before the following lines.

> I would like to address this issue and, perhaps the one with the docker images having more helpful tagging. It would be best to have tags sync'd between docker and pypi.

You're absolutely right. All the versions across different services **should** have the same tag.
This will prevent huge headaches!

> How does commit-based tagging work with pip where there is an implied ordering of the tags to make >= operations meaningful ?

Maybe I created some confusion with the hash-based tagging proposal.
You should upload only released versions of your software to pypi, and not using hash-tagged releases.
If any user would want to run a specific version of the software (under a non-tagged commit), they can just download the repository and install it with pip from the local repo.
Moreover, you could run:
```
pip https://github.com/username/my-repo/archive/master.zip
```
It will download the `master` branch and install the software. Which version will you get? The one in the `master`'s `HEAD`.
I don't know if this will work with `stripy` because the `setup.py` is not on the root of the repo, but we can see it in the future. Just wanted to show that `pip` does not need a specific release, it can work on any commit of the repo.

So, you'll not have any problems by using the `>=` syntax if you upload only releases to pypi following a versioning semantic.

On the other hand, Docker images has to be manually created. So what happens if you want to test if a Docker image works as expected but don't want to create a release only to do that? In those cases I would use hash-tagged Docker images. This would make tracking very easy and won't confuse users which Docker version they should run.

A different thing happens with Binder. You could create binders either for releases or for branches, so you could have binders running immutable snapshots (releases) or linked to the latest commit on any branch.

**Comment by santisoler** [comment]
> Happy to address this offline if it will blow out the review thread.

I think JOSS wants the review process to be open, so I would keep our discussions on Issues and PRs.
I think it's important because it lets editors to monitor if any reviewer is violating the Code of Conduct.

So feel free to fill the issues with a lot of comments!

**Comment by santisoler** [comment]
Please let me know if I didn't explain myself well on any topic.

**Comment by lmoresi** [comment]
I have restructured the repo to match your suggestions and (after quite a bit of digging through the binderhub / repo2docker repositories) managed to hide the ugly and incompatible binder configuration options that we previously needed branching to manage. Your advice is helpful here and does actually mean we can automate the container process. 

My question regarding the tagging was indeed aimed at pypi and so that's probably all fine after your clarification - the use of pip to grab specific repo commits is also fine for ensuring that we have precise reproducibility. 

I think we are good to go on this one. Is there anything else ?

**Comment by santisoler** [comment]
Thanks for taking my proposals into consideration.
I think this issue is already solved, so I'll close it.
If any other issue comes up regarding the installation instructions, we could open a new issue in the future.
