### ISSUE TITLE
[REVIEW] Presence of litho1pt0 on stripy repository

### ISSUE THREAD

**Issue by santisoler** [underworldcode/stripy#26]
Part of https://github.com/openjournals/joss-reviews/issues/1410

I'm a little bit confused about the presence of `litho1pt0` source code on `stripy` repo.
I can see the vinculation between both packages, and the importance of showing how `stripy` is a great companion for the Litho1.0 dataset.
Nevertheless, it's not a good practice to include several packages into a single repo.
Having one repository for each package makes maintenance a lot easier and makes very clear which is the goal of each package.
For example, `litho1pt0` needs `stripy`, but `stripy` could be applied to other problems besides the ones that `litho1pt0` tries to solve.
So keeping `stripy` as a separated package would be helpful for users that desire to use it for solving these other problems.

Another approach would be to merge both packages into a single one.
This could be done including the `litho1pt0` source code into the `stripy` code.
Nevertheless, I don't think this is the best solution for your case: it would mislead the goal of `stripy` making it very tied to `litho1pt0` applications rather than the actual Python interface to `TRIPACK` and `STRIPACK`.

If you choose to create separated packages, you can still keep the Notebooks containing Litho 1.0 examples although `litho1pt0` should be installed as a (secondary) dependency (see #24).
The same goes for `stripy` on the `litho1pt0` repo: it should be included as a main dependency for `litho1pt0`.

I'm glad to hear your opinions about this!

**Comment by lmoresi** [comment]
OK - this is a historical artifact. Litho1pt0 was the original code and stripy was broken out of it. I would be happy to remove this and create another repo for litho1pt0 given the direction stripy has now taken. [[ @brmather , we should do all the other matters regarding tests and reorganisation first so that litho1pt0 benefits from all the advice we are receiving in this review ]]

**Comment by santisoler** [comment]
:+1: In fact you could submit another paper with `litho1pt0` to JOSS :tada:

**Comment by brmather** [comment]
Yes, I agree it makes sense to split `litho1pt0` out of stripy. The documentation for it is not up to the same standard as `stripy` so this is something we could work on separately. Thanks @santisoler for the suggestion.

**Comment by lmoresi** [comment]
In the proposed restructure, litho1pt0 is gone and I have created the relevant repository so that the history is not lost. I think we can close this issue
