### ISSUE TITLE
[REVIEW] Litho1pt0 importation is being tested

### ISSUE THREAD

**Issue by santisoler** [underworldcode/stripy#36]
Part of https://github.com/openjournals/joss-reviews/issues/1410

Litho1pt0 has been moved away from Stripy repository, although its importation it's still being tested on [test/test_0_imports.py](https://github.com/underworldcode/stripy/blob/master/tests/test_0_imports.py).
I would suggest to remove it until `litho1pt0` is nicely packaged and could be installed though pypi.

What do you think?

**Comment by santisoler** [comment]
Ok. I found that `litho1pt0` is still available on pypi.
So, maybe we should just add it to the `README.md`.

**Comment by brmather** [comment]
Alright, I've just added it with your pull request #34
