### ISSUE TITLE
gdal library is too complicated

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/stripy#39]
I suggest we migrate to imageio which is far simpler to install and maintain. It does not need the complicated binary / gcc built dependencies of gdal.

I might not be able to recommend this for the processing of satellite images etc because gdal does give access to the geo transform data but for our demonstrations in stripy it works fine. 

There are some examples in the lavavu texture mapping for reference sake.

**Comment by brmather** [comment]
But `cartopy` requires gdal libraries...

**Comment by lmoresi** [comment]
hmmm … so much for that idea. It is easier to use imageio for the image import though and is more legible.



Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 6 Jun 2019, 4:00 PM +1000, Ben Mather <notifications@github.com>, wrote:

But cartopy requires gdal libraries...

**Comment by brmather** [comment]
Yes, and scipy are deprecating their `imread` function, so alternatives like imageio are now necessary!

**Comment by lmoresi** [comment]
Python gdal is not really needed for cartopy ... the missing functionality if we switch to imageio is the geotransform extraction from a geotiff.  That's the kind of thing that is not important for demonstrating stripy even if it is vital for the eventual applications.

**Comment by brmather** [comment]
Ah - I was getting confused with GEOS. But that's a much simpler installation than GDAL. The geotransformation stuff is probably not even that important considering all our geotiffs use a global extent. Removing GDAL should trim down the docker image size too.

**Comment by lmoresi** [comment]
You still need the goal library but not the python layer of dgalwey which can be a bit fussy
On 17 Jul 2019, 17:19 -0700, Ben Mather <notifications@github.com>, wrote:

Ah - I was getting confused with GEOS. But that's a much simpler installation than GDAL. The geotransformation stuff is probably not even that important considering all our geotiffs use a global extent. Removing GDAL should trim down the docker image size too.

**Comment by lmoresi** [comment]
One last comment and then I am going to close this. The PIL library does allow us to extract the metadata from a tif and access the geotransforms that are embedded. It is not as elegant as the gdal solution but is helpful if we want to include a demo that uses non-global data.
