### ISSUE TITLE
Links to notebooks are broken?

### ISSUE THREAD

**Issue by michaelaye** [underworldcode/stripy#51]
This looks like an interesting project.
But I get 404s on the notebooks linked in the readme?

**Comment by julesghub** [comment]
Thanks for raising this @michaelaye. I have submitted a PR to fix this - #52. Should be merged in soon.

Meanwhile you can use this branch without 404s - https://github.com/underworldcode/stripy/tree/fix-readme-links

**Comment by brmather** [comment]
Sorry for that @michaelaye - those links must have broken after a directory restructure some time ago. I have merged #52 so those links now work from the `master` branch.
