### ISSUE TITLE
What happened to the API docs?

### ISSUE THREAD

**Issue by brmather** [underworldcode/stripy#53]
Something must be overwritten with the Underworld website because I can't find the API docs anymore :cry:

**Comment by lmoresi** [comment]
I think we need to publish those docs in a new location ... the website overhaul has migrated everything away from the github pages.

**Comment by brmather** [comment]
Looking a bit further into it, they're located at https://underworldcode.github.io/stripy/
I'll update the link in the README.

**Comment by lmoresi** [comment]
I just fixed all the redirects to allow that link to show up.
