### ISSUE TITLE
Non-deterministic tests

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/stripy#69]
Every once in a while we get a failed test because:

```
E           ValueError: ierr=-2 in trmesh
E           the first three nodes are collinear.
E           Set permute to True or reorder nodes manually.
```

We should not let this get triggered in testing

**Comment by brmather** [comment]
After a couple of refinements the `square_mesh` class would occasionally raise this error after a couple of refinements - despite the point order being randomised. I fixed this in 5e46c8550c3127a4203b2e2dcd4ca5a8a09edd6e by swapping the first point with the last point.
