### ISSUE TITLE
Stripy Import error

### ISSUE THREAD

**Issue by koekoekk** [underworldcode/stripy#74]
I am trying to use Stripy. I was able to install Stripy with `pip install stripy`, after I installed gfortran with MinGW.
However, after importing the module stripy I get the following import error message:

> ImportError: DLL load failed while importing _stripack: The specified module could not be found.

I cannot find what could cause this error, so I am hoping you could help me on solving this error.

I am using Python 3.7

My stripy package directory looks [as follows](https://imgur.com/yeVhPNo)

**Comment by lmoresi** [comment]
gfortran strikes again. @rbeucher - do we have a conda build that we could suggest instead that might be an alternative ?

**Comment by rbeucher** [comment]
Hi @koekoekk  @lmoresi 

We don't have a windows build. I can look into it.

**Comment by rbeucher** [comment]
Hi @koekoekk 

I have made a win-64 binary. Can you try to install it from your conda installation?

Make sure you have conda-forge in the channels.

```
conda config --add channels conda-forge
conda install -c underworldcode stripy
```

I have tried on that machine and it looks like it is working OK.
Note that we only have a binary for python3.7 so make sure that your anaconda install is up to date.

Romain

**Comment by koekoekk** [comment]
Hi @rbeucher,
This works for me with python 3.7. Thank you!

**Comment by rbeucher** [comment]
Great, glad that works
